import pytest

"""def test_exception():
    with pytest.raises(Exception) as e:
        funcion_with_exception(0)
"""